spring.datasource.url=jdbc:postgresql://localhost:5432/e_sign
spring.datasource.username=rara_api_user
spring.datasource.password=pa3s@Nixi

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB