spring.application.name=khkatian-services
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/e_sign
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update